name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Install libcurl development package
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
    
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/gwas2vcf
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gwas2vcf:${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
